name: Publish Packages
on:
  release:
    types: [published, created, edited]

jobs:
  release_npm:
    runs-on: ubuntu-latest
    name: Publish Package to NPM
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      - name: Install Packages
        run: |
          npm ci
      - name: Build Package
        run: npm run build
      - name: Prepare Package
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_PUBLISH }}
      - name: Upload Package
        run: npm publish
